apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  hostname: busybox-1
  subdomain: default
  containers:
    - image: busybox
      command:
        - sleep
        - "3600"
      name: busybox
#  nodeSelector:
#    role: services
